{
  "c_id" : 3,
  "c_parentid" : 2,
  "c_position" : 0,
  "c_left" : 3,
  "c_right" : 4,
  "c_level" : 2,
  "c_title" : "Leaf Node",
  "c_type" : "default",
  "ref" : 0,
  "copy" : 0,
  "multiCounter" : 0,
  "status" : 0,
  "ajaxMessage" : null,
  "childcount" : "NoChild",
  "searchStr" : null,
  "idif" : 0,
  "ldif" : 0,
  "spaceOfTargetNode" : 0,
  "c_idsByChildNodeFromNodeById" : null,
  "fixCopyId" : 0,
  "fixCopyPosition" : 0,
  "rightPositionFromNodeByRef" : 0,
  "nodeById" : null,
  "idifLeft" : 0,
  "idifRight" : 0,
  "id" : 0,
  "attr" : {
    "rel" : "default",
    "id" : "node_3"
  },
  "copyBooleanValue" : false,
  "calTime" : "2017-09-22 17:30:29",
  "topSpecName" : "상위 스펙 명",
  "topSpec1Title" : "상위 스펙 이름1",
  "topSpec1Amount" : 313,
  "topSpec1Percent" : 31.0,
  "topSpec1Trend" : 31,
  "topSpec1Graph" : 31.0,
  "topSpec2Title" : "상위 스펙 이름2",
  "topSpec2Amount" : 313,
  "topSpec2Percent" : 31.0,
  "topSpec2Trend" : 31,
  "topSpec2Graph" : 31.0,
  "topSpec3Title" : "상위 스펙 이름3",
  "topSpec3Amount" : 313,
  "topSpec3Percent" : 31.0,
  "topSpec3Trend" : 31,
  "topSpec3Graph" : 31.0,
  "topSpec4Title" : "상위 스펙 이름4",
  "topSpec4Amount" : 313,
  "topSpec4Percent" : 31.0,
  "topSpec4Trend" : 31,
  "topSpec4Graph" : 31.0,
  "topSpec5Title" : "상위 스펙 이름5",
  "topSpec5Amount" : 313,
  "topSpec5Percent" : 31.0,
  "topSpec5Trend" : 31,
  "topSpec5Graph" : 31.0,
  "midSpecName" : "중위 스펙 명",
  "midSpec1Title" : "중위 스펙 이름1",
  "midSpec1Amount" : 313,
  "midSpec1Percent" : 13.0,
  "midSpec1Trend" : 31,
  "midSpec1Graph" : 13.0,
  "midSpec2Title" : "중위 스펙 이름2",
  "midSpec2Amount" : 313,
  "midSpec2Percent" : 13.0,
  "midSpec2Trend" : 31,
  "midSpec2Graph" : 13.0,
  "midSpec3Title" : "중위 스펙 이름3",
  "midSpec3Amount" : 313,
  "midSpec3Percent" : 13.0,
  "midSpec3Trend" : 31,
  "midSpec3Graph" : 13.0,
  "midSpec4Title" : "중위 스펙 이름4",
  "midSpec4Amount" : 313,
  "midSpec4Percent" : 13.0,
  "midSpec4Trend" : 31,
  "midSpec4Graph" : 13.0,
  "midSpec5Title" : "중위 스펙 이름5",
  "midSpec5Amount" : 313,
  "midSpec5Percent" : 13.0,
  "midSpec5Trend" : 31,
  "midSpec5Graph" : 13.0,
  "botSpecName" : "하위 스펙 명",
  "botSpec1Title" : "하위 스펙 이름1",
  "botSpec1Amount" : 313,
  "botSpec1Percent" : 3.0,
  "botSpec1Trend" : 31,
  "botSpec1Graph" : 3.0,
  "botSpec2Title" : "하위 스펙 이름2",
  "botSpec2Amount" : 313,
  "botSpec2Percent" : 3.0,
  "botSpec2Trend" : 31,
  "botSpec2Graph" : 3.0,
  "botSpec3Title" : "하위 스펙 이름3",
  "botSpec3Amount" : 313,
  "botSpec3Percent" : 3.0,
  "botSpec3Trend" : 31,
  "botSpec3Graph" : 3.0,
  "botSpec4Title" : "하위 스펙 이름4",
  "botSpec4Amount" : 313,
  "botSpec4Percent" : 3.0,
  "botSpec4Trend" : 31,
  "botSpec4Graph" : 3.0,
  "botSpec5Title" : "하위 스펙 이름5",
  "botSpec5Amount" : 313,
  "botSpec5Percent" : 3.0,
  "botSpec5Trend" : 31,
  "botSpec5Graph" : 3.0,
  "copied" : false,
  "data" : "Leaf Node",
  "state" : "leafNode"
}
