{
  "c_id" : 3,
  "c_parentid" : 2,
  "c_position" : 0,
  "c_left" : 3,
  "c_right" : 4,
  "c_level" : 2,
  "c_title" : "Aggregate sum Result",
  "c_type" : "default",
  "ref" : 0,
  "copy" : 0,
  "multiCounter" : 0,
  "status" : 0,
  "ajaxMessage" : null,
  "childcount" : "NoChild",
  "searchStr" : null,
  "idif" : 0,
  "ldif" : 0,
  "spaceOfTargetNode" : 0,
  "c_idsByChildNodeFromNodeById" : null,
  "fixCopyId" : 0,
  "fixCopyPosition" : 0,
  "rightPositionFromNodeByRef" : 0,
  "nodeById" : null,
  "idifLeft" : 0,
  "idifRight" : 0,
  "id" : 0,
  "attr" : {
    "rel" : "default",
    "id" : "node_3"
  },
  "copyBooleanValue" : false,

  "calTime" : "2017-09-06 15:13:00",

  "topName" : "galxy 8",
  "topNumberOfAdvantages" : 31333,
  "topLikeCount" : 1325,
  "topTotalRegisteredPosts" : 33111,
  "topRegisteredHashTag" : 3,
  "topGraphPercent" : 63,
  "topVersusScore" : 1987,

  "midName" : "LG V30",
  "midNumberOfAdvantages" : 23,
  "midLikeCount" : 9,
  "midTotalRegisteredPosts" : 24,
  "midRegisteredHashTag" : 2,
  "midGraphPercent" : 33,
  "midVersusScore" : 945,

  "botName" : "iPhone 8",
  "botNumberOfAdvantages" : 13,
  "botLikeCount" : 4,
  "botTotalRegisteredPosts" : 54,
  "botRegisteredHashTag" : 2,
  "botGraphPercent" : 4,
  "botVersusScore" : 576,


  "totalTraffic" : 0,
  "uniqueVisit" : 0,
  "revisitCount" : 0,
  "pageView" : 0,
  "totalArticle" : 0,
  "totalLikeCount" : 0,
  "totalSpecCount" : 0,
  "totalHashCount" : 0,
  "standardError" : 0,
  "equilibriumAssumption" : 0,
  "probability" : 0,
  "lowerLimit" : 0,
  "higherLimit" : 0,
  "distributionTResult" : 0,
  "state" : "leafNode",
  "data" : "Aggregate sum Result",
  "copied" : false
}
