[ {
  "c_id" : 2,
  "c_parentid" : 1,
  "c_position" : 0,
  "c_left" : 2,
  "c_right" : 27,
  "c_level" : 1,
  "c_title" : "First Child",
  "c_type" : "drive",
  "ref" : 0,
  "copy" : 0,
  "multiCounter" : 0,
  "status" : 0,
  "ajaxMessage" : null,
  "childcount" : "InChild",
  "searchStr" : null,
  "idif" : 0,
  "ldif" : 0,
  "spaceOfTargetNode" : 0,
  "c_idsByChildNodeFromNodeById" : null,
  "fixCopyId" : 0,
  "fixCopyPosition" : 0,
  "rightPositionFromNodeByRef" : 0,
  "nodeById" : null,
  "idifLeft" : 0,
  "idifRight" : 0,
  "id" : 0,
  "attr" : {
    "rel" : "drive",
    "id" : "node_2"
  },
  "copyBooleanValue" : false,
  "copied" : false,
  "data" : "First Child",
  "state" : "closed"
} ]