[ {
  "c_id" : 3,
  "c_parentid" : 4,
  "c_position" : 0,
  "c_left" : 4,
  "c_right" : 5,
  "c_level" : 3,
  "c_title" : "Leaf Node",
  "c_type" : "default",
  "ref" : 0,
  "copy" : 0,
  "multiCounter" : 0,
  "status" : 0,
  "ajaxMessage" : null,
  "childcount" : "NoChild",
  "searchStr" : null,
  "idif" : 0,
  "ldif" : 0,
  "spaceOfTargetNode" : 0,
  "c_idsByChildNodeFromNodeById" : null,
  "fixCopyId" : 0,
  "fixCopyPosition" : 0,
  "rightPositionFromNodeByRef" : 0,
  "nodeById" : null,
  "idifLeft" : 0,
  "idifRight" : 0,
  "id" : 0,
  "attr" : {
    "rel" : "default",
    "id" : "node_3"
  },
  "copyBooleanValue" : false,
  "copied" : false,
  "data" : "Leaf Node",
  "state" : "leafNode"
}, {
  "c_id" : 50,
  "c_parentid" : 4,
  "c_position" : 1,
  "c_left" : 6,
  "c_right" : 7,
  "c_level" : 3,
  "c_title" : "operationDB",
  "c_type" : "default",
  "ref" : 0,
  "copy" : 0,
  "multiCounter" : 0,
  "status" : 0,
  "ajaxMessage" : null,
  "childcount" : "NoChild",
  "searchStr" : null,
  "idif" : 0,
  "ldif" : 0,
  "spaceOfTargetNode" : 0,
  "c_idsByChildNodeFromNodeById" : null,
  "fixCopyId" : 0,
  "fixCopyPosition" : 0,
  "rightPositionFromNodeByRef" : 0,
  "nodeById" : null,
  "idifLeft" : 0,
  "idifRight" : 0,
  "id" : 0,
  "attr" : {
    "rel" : "default",
    "id" : "node_50"
  },
  "copyBooleanValue" : false,
  "copied" : false,
  "data" : "operationDB",
  "state" : "leafNode"
} ]
