[ {
  "c_id" : 2,
  "c_parentid" : 1,
  "c_position" : 0,
  "c_left" : 2,
  "c_right" : 17,
  "c_level" : 1,
  "c_title" : "모니터링 호스트 목록",
  "c_type" : "drive",
  "ref" : 0,
  "copy" : 0,
  "multiCounter" : 0,
  "status" : 0,
  "ajaxMessage" : null,
  "childcount" : "InChild",
  "searchStr" : null,
  "idif" : 0,
  "ldif" : 0,
  "spaceOfTargetNode" : 0,
  "c_idsByChildNodeFromNodeById" : null,
  "fixCopyId" : 0,
  "fixCopyPosition" : 0,
  "rightPositionFromNodeByRef" : 0,
  "nodeById" : null,
  "idifLeft" : 0,
  "idifRight" : 0,
  "id" : 0,
  "attr" : {
    "rel" : "drive",
    "id" : "node_2"
  },
  "c_monitor_name" : "c_monitor_name",
  "c_monitor_update_date" : "c_monitor_update_date",
  "c_monitor_update_beatname" : "c_monitor_update_beatname",
  "c_monitor_device_hostname" : "c_monitor_device_hostname",
  "c_monitor_device_ip" : "c_monitor_device_ip",
  "c_monitor_url_filebeat" : "c_monitor_url_filebeat",
  "c_monitor_url_topbeat" : "c_monitor_url_topbeat",
  "c_monitor_url_metricbeat" : "c_monitor_url_metricbeat",
  "c_monitor_url_packetbeat" : "c_monitor_url_packetbeat",
  "c_monitor_url_heartbeat" : "c_monitor_url_heartbeat",
  "c_monitor_url_apm" : "c_monitor_url_apm",
  "c_monitor_url_scouter" : "c_monitor_url_scouter",
  "copied" : false,
  "data" : "모니터링 호스트 목록",
  "state" : "closed"
} ]