{
  "result" : [ {
    "c_id" : 115,
    "c_parentid" : 2,
    "c_position" : 0,
    "c_left" : 3,
    "c_right" : 6,
    "c_level" : 2,
    "c_title" : "핸드폰",
    "c_type" : "folder",
    "ref" : 0,
    "copy" : 0,
    "multiCounter" : 0,
    "status" : 0,
    "ajaxMessage" : null,
    "childcount" : "InChild",
    "searchStr" : null,
    "idif" : 0,
    "ldif" : 0,
    "spaceOfTargetNode" : 0,
    "c_idsByChildNodeFromNodeById" : null,
    "fixCopyId" : 0,
    "fixCopyPosition" : 0,
    "rightPositionFromNodeByRef" : 0,
    "nodeById" : null,
    "idifLeft" : 0,
    "idifRight" : 0,
    "id" : 0,
    "attr" : {
      "rel" : "folder",
      "id" : "node_115"
    },
    "copyBooleanValue" : false,
    "menuId" : null,
    "userId" : null,
    "userLevel" : null,
    "writeTime" : null,
    "selectedCompareItem" : null,
    "contentsBody" : null,
    "hashTags" : null,
    "likeCount" : null,
    "hateCount" : null,
    "hiddenYN" : null,
    "reportYN" : null,
    "state" : "closed",
    "data" : "핸드폰",
    "copied" : false
  } ],
  "paginationInfo" : {
    "currentPageNo" : 1,
    "recordCountPerPage" : 1,
    "pageSize" : 10,
    "totalRecordCount" : 1,
    "totalPageCount" : 1,
    "firstPageNoOnPageList" : 1,
    "lastPageNoOnPageList" : 1,
    "firstRecordIndex" : 0,
    "lastRecordIndex" : 1,
    "firstPageNo" : 1,
    "lastPageNo" : 1
  }
}
